plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: example
title: Example Plugin
description: Example plugin for testing
version: 1.0.0
vendor: rapid7
status: []
tags: []
hub_tags:
  use_cases: []
  keywords: []
  features: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/example
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: http://www.rapid7.com
enable_cache: true

types:
  person:
    first_name:
      title: First Name
      type: string
    last_name:
      title: Last Name
      type: string

connection:
  hostname:
    title: Host
    description: Enter the hostname
    type: string
    required: true
  port:
    description: Enter the port
    type: integer
    default: 80
    required: true
  username:
    description: Enter the username
    type: string
    required: true

triggers:
  emit_greeting:
    title: Trigger a New Greeting
    description: Triggers a greeting every interval
    input:
      interval:
        description: How frequently (in seconds) to trigger a greeting
        type: integer
        default: 15
        required: true
    output:
      greeting:
        required: true
        type: person

actions:
  say_goodbye:
    title: Say Goodbye
    description: Emit say goodbye message
    input:
      name:
        type: string
        description: Name to say goodbye to
        required: true
    output:
      message:
        title: Message
        type: string
        required: true
  say_hello:
    title: Say Hello
    description: Emit say hello message
    input:
      name:
        type: string
        description: Name to say hello to
        required: true
    output:
      message:
        title: Message
        type: string
        required: true